contact_links:
  - name: 🤔 Questions & Discussions
    url: https://github.com/alanlu-dev/notion-kit/discussions/new?category=general
    about: Use GitHub discussions for forum-like discussions and questions.
